---
- name: "Check for binary"
  ansible.builtin.stat:
    path: "{{ chrony_exporter_install_dir }}/{{ chrony_exporter_bin_name }}"
  changed_when: false
  register: __installed_bin

- name: "Sources install tasks"
  ansible.builtin.include_tasks: install_src.yml
  when: chrony_exporter_install_method == "src"

- name: "Configuring systemd"
  ansible.builtin.template:
    src: chrony_exporter.service.j2
    dest: "/etc/systemd/system/chrony_exporter.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Restart chrony_exporter"
  register: __config_systemd

- name: "Start service"
  ansible.builtin.service:
    name: chrony_exporter
    state: started
    enabled: true
    daemon_reload: true
  when:
    - chrony_exporter_start_service
    - __config_systemd.changed
